development:
 adapter: postgresql
 database: micro-learning-development

test:
 adapter: postgresql
 database: micro-learning-test

production:
 adapter: postgresql
 database: micro-learning-production